name: Ecommerce API

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Create .env.test file
        run: |
          echo "JWT_ACCESS_TOKEN_SECRET=secret" >> .env
          echo "JWT_REFRESH_TOKEN_SECRET=secret2" >> .env

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --config.frozen-lockfile=true --include=dev

      - name: ESlint
        run: pnpm run eslint:check

      - name: Prettier
        run: pnpm run prettier:check

  migrate:
    runs-on: ubuntu-latest
    needs: check
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --config.frozen-lockfile=true --include=dev

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
          envkey_JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
          envkey_ASAAS_API_KEY: ${{ secrets.ASAAS_API_KEY }}
          envkey_EMAIL_USER: ${{ secrets.EMAIL_USER }}
          envkey_EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

      - name: Run migrations
        run: pnpm drizzle-kit migrate

  deploy:
    runs-on: ubuntu-latest
    needs: migrate
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Deploy to Production
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
